INSERT INTO negozio.prodotto VALUES (1, 'giacca', 'Verri', 'moda', 140.50);
INSERT INTO negozio.prodotto VALUES (2, 'pantaloni', 'Armani', 'moda', 180.00);
INSERT INTO negozio.prodotto VALUES (3, 'cintura', 'Versace', 'moda', 90.00);
INSERT INTO negozio.prodotto VALUES (4, 'giacca', 'Trussardi', 'moda', 220.00);
INSERT INTO negozio.prodotto VALUES (5, 'pantaloni', 'Trussardi', 'moda', 130.00);
INSERT INTO negozio.prodotto VALUES (6, 'cintura', 'Armani', 'casual', 99.50);
INSERT INTO negozio.prodotto VALUES (7, 'pantaloni', 'Trussardi', 'casual', 75.00);
INSERT INTO negozio.prodotto VALUES (8, 'giacca', 'Armani', 'casual', 135.00);
INSERT INTO negozio.prodotto VALUES (9, 'giacca', 'Trussardi', 'casual', 105.50);
INSERT INTO negozio.prodotto VALUES (10, 'camicia', 'Versace', 'denim', 89.00);
INSERT INTO negozio.prodotto VALUES (11, 'pantaloni', 'Versace', 'denim', 103.00);
INSERT INTO negozio.prodotto VALUES (12, 'cintura', 'Versace', 'denim', 70.00);

INSERT INTO negozio.vetrina VALUES (1, 'rosa', 'donna', 180);
INSERT INTO negozio.vetrina VALUES (2, 'blu', 'uomo', 140);
INSERT INTO negozio.vetrina VALUES (3, 'giallo', 'bambino', 120);
INSERT INTO negozio.vetrina VALUES (4, 'viola', 'donna', 90);

INSERT INTO negozio.presenza VALUES (1, 3, 1);
INSERT INTO negozio.presenza VALUES (1, 4, 4);
INSERT INTO negozio.presenza VALUES (1, 6, 2);
INSERT INTO negozio.presenza VALUES (2, 1, 3);
INSERT INTO negozio.presenza VALUES (2, 2, 1);
INSERT INTO negozio.presenza VALUES (2, 5, 5);
INSERT INTO negozio.presenza VALUES (2, 7, 9);
INSERT INTO negozio.presenza VALUES (3, 6, 2);
INSERT INTO negozio.presenza VALUES (3, 10, 1);
INSERT INTO negozio.presenza VALUES (3, 11, 4);
INSERT INTO negozio.presenza VALUES (3, 12, 1);
INSERT INTO negozio.presenza VALUES (4, 1, 2);
INSERT INTO negozio.presenza VALUES (4, 4, 4);