SET search_path TO prodotti;
/*
--PRIMA PARTE--
--a
SELECT PRODOTTO.*, INVENTARIO.prezzo FROM INVENTARIO 
JOIN PRODOTTO ON PRODOTTO.codP = INVENTARIO.prodotto
WHERE INVENTARIO.magazzino = 'M11'
ORDER BY PRODOTTO.categoria, INVENTARIO.prezzo DESC;

--b
SELECT DISTINCT MAGAZZINO.codM, MAGAZZINO.indirizzo FROM MAGAZZINO
JOIN INVENTARIO ON INVENTARIO.magazzino = MAGAZZINO.codM 
JOIN PRODOTTO ON INVENTARIO.prodotto = PRODOTTO.codP
WHERE MAGAZZINO.citta = 'Milano' 
AND PRODOTTO.categoria = 'elettrodomestici' 
AND INVENTARIO.quantita > 20;

--c
SELECT MAGAZZINO.codM, MAGAZZINO.citta FROM MAGAZZINO
JOIN INVENTARIO ON MAGAZZINO.codM = INVENTARIO.magazzino
JOIN PRODOTTO ON PRODOTTO.codP = INVENTARIO.prodotto
WHERE PRODOTTO.nome = 'spaghetti';

--SECONDA PARTE--
--d
SELECT MAGAZZINO.codM FROM MAGAZZINO
WHERE NOT EXISTS( 
    SELECT * FROM INVENTARIO
    WHERE MAGAZZINO.codM = INVENTARIO.magazzino
);
*/

--e
SELECT MAGAZZINO.codM FROM MAGAZZINO
WHERE NOT EXISTS (      --magazzini vuoti
    SELECT * FROM INVENTARIO
    WHERE MAGAZZINO.codM = INVENTARIO.magazzino
 ) OR NOT EXISTS (       --magazzini senza un prodotto tipo 'alimentari'
    SELECT * FROM INVENTARIO
    JOIN PRODOTTO ON PRODOTTO.codP = INVENTARIO.prodotto
    WHERE PRODOTTO.categoria = 'alimentari' AND INVENTARIO.magazzino = MAGAZZINO.codM
);
